/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/entranceBioTech.glb -o src/components/BioTech.jsx -k -K -r public 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import * as THREE from "three";
import { useEffect } from "react";

export function BioTech(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/entranceBioTech.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(materials).forEach((mat) => {
      mat.side = THREE.DoubleSide;
    });
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="rp_nathan_animated_003_walking"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group name="rp_nathan_animated_003_walking_CTRL">
            <group name="Armature" scale={2.581}>
              <primitive object={nodes.rp_nathan_animated_003_walking_root} />
              <skinnedMesh
                name="rp_nathan_animated_003_walking_geo"
                geometry={nodes.rp_nathan_animated_003_walking_geo.geometry}
                material={materials.rp_nathan_animated_003_mat}
                skeleton={nodes.rp_nathan_animated_003_walking_geo.skeleton}
              />
            </group>
          </group>
          <group name="rp_nathan_animated_003_walking_geoGRP" />
        </group>
        <mesh
          name="entrance_stairs"
          geometry={nodes.entrance_stairs.geometry}
          material={materials["Material.004"]}
          scale={[0.308, 0.308, 0.495]}
        />
        <mesh
          name="EntranceRedHandbarInner1"
          geometry={nodes.EntranceRedHandbarInner1.geometry}
          material={materials.redRod}
          position={[24.432, 6.678, -6.7]}
          rotation={[0, 0, 0.326]}
          scale={[3.137, 0.18, 0.187]}
        />
        <mesh
          name="EntranceRedHandbarInner2"
          geometry={nodes.EntranceRedHandbarInner2.geometry}
          material={materials.redRod}
          position={[24.432, 6.678, 6.7]}
          rotation={[0, 0, 0.326]}
          scale={[3.137, 0.18, 0.187]}
        />
        <mesh
          name="EntranceRedHandbarOuter1"
          geometry={nodes.EntranceRedHandbarOuter1.geometry}
          material={materials.redRod}
          position={[18.109, 4.495, -9]}
          rotation={[0, 0, 0.326]}
          scale={[3.137, 0.18, 0.187]}
        />
        <mesh
          name="EntranceRedHandbarOuter2"
          geometry={nodes.EntranceRedHandbarOuter2.geometry}
          material={materials.redRod}
          position={[18.109, 4.495, 9]}
          rotation={[0, 0, 0.326]}
          scale={[3.137, 0.18, 0.187]}
        />
        <mesh
          name="entranceGround"
          geometry={nodes.entranceGround.geometry}
          material={
            materials[
              "asset_base_id:3e8f92f3-2840-47af-afaa-8cd11f9bc641 asset_ty"
            ]
          }
          position={[0, -0.104, 0]}
          scale={3.696}
        />
        <mesh
          name="EntranceWhiteSidebarOOTop1"
          geometry={nodes.EntranceWhiteSidebarOOTop1.geometry}
          material={
            materials[
              "asset_base_id:3e8f92f3-2840-47af-afaa-8cd11f9bc641 asset_type:m"
            ]
          }
          position={[18.109, 3.106, -14.067]}
          rotation={[0, 0, 0.326]}
          scale={[3.137, 0.18, 1.002]}
        />
        <mesh
          name="EntranceWhiteSidebarOO1"
          geometry={nodes.EntranceWhiteSidebarOO1.geometry}
          material={nodes.EntranceWhiteSidebarOO1.material}
          position={[26.145, 4.248, -14.035]}
          rotation={[0, 0, 0.325]}
          scale={[3.86, 1, 0.831]}
        />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials["Yellow Plaster"]}
          position={[29.431, 23.748, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[23.627, 23.627, 53.709]}
        />
        <mesh
          name="EntranceWhiteSidebarOOTop1001"
          geometry={nodes.EntranceWhiteSidebarOOTop1001.geometry}
          material={nodes.EntranceWhiteSidebarOOTop1001.material}
          position={[18.115, 3.171, 14.065]}
          rotation={[0, 0, 0.326]}
          scale={[3.137, 0.18, 1.002]}
        />
        <mesh
          name="EntranceWhiteSidebarOO1001"
          geometry={nodes.EntranceWhiteSidebarOO1001.geometry}
          material={nodes.EntranceWhiteSidebarOO1001.material}
          position={[26.145, 4.248, 14.035]}
          rotation={[0, 0, 0.325]}
          scale={[3.86, 1, 0.831]}
        />
        <mesh
          name="OuterDagadiWall2"
          geometry={nodes.OuterDagadiWall2.geometry}
          material={materials.Stone}
          position={[29.156, 2.563, 34.102]}
          scale={[1, 3.217, 20.461]}
        />
        <mesh
          name="OuterDagadiWall1"
          geometry={nodes.OuterDagadiWall1.geometry}
          material={materials.Stone}
          position={[29.156, 2.563, -34.937]}
          scale={[1, 3.217, 20.461]}
        />
        <mesh
          name="OuterWalkway1"
          geometry={nodes.OuterWalkway1.geometry}
          material={
            materials[
              "asset_base_id:3e8f92f3-2840-47af-afaa-8cd11f9bc641 asset_ty"
            ]
          }
          position={[25.583, -0.109, -35.116]}
          scale={[3.049, 0.34, 20.493]}
        />
        <mesh
          name="OuterWalkway2"
          geometry={nodes.OuterWalkway2.geometry}
          material={
            materials[
              "asset_base_id:3e8f92f3-2840-47af-afaa-8cd11f9bc641 asset_ty"
            ]
          }
          position={[25.583, -0.109, 34.514]}
          scale={[3.049, 0.34, 20.493]}
        />
        <mesh
          name="WhiteBGPattiFirstFloor"
          geometry={nodes.WhiteBGPattiFirstFloor.geometry}
          material={
            materials[
              "asset_base_id:3e8f92f3-2840-47af-afaa-8cd11f9bc641 asset_type:m"
            ]
          }
          position={[29.431, 23.748, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[23.627, 23.627, 53.709]}
        />
        <mesh
          name="GlassLower2"
          geometry={nodes.GlassLower2.geometry}
          material={materials.Glass}
          position={[29.581, 11.416, 33.655]}
          scale={[0.2, 5.985, 20.117]}
        >
          <mesh
            name="GlassSupLower2"
            geometry={nodes.GlassSupLower2.geometry}
            material={materials.glasswindowsSupport}
            position={[-1.785, 0, -0.01]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.923, 5, 1.001]}
          />
        </mesh>
        <mesh
          name="GlassUpper1"
          geometry={nodes.GlassUpper1.geometry}
          material={materials.Glass}
          position={[29.071, 28.449, -33.538]}
          scale={[0.2, 5.313, 11.828]}
        >
          <mesh
            name="GlassSupUpper1"
            geometry={nodes.GlassSupUpper1.geometry}
            material={materials.glasswindowsSupport}
            position={[-1.785, -0.034, -0.01]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[1.04, 5, 1.702]}
          />
        </mesh>
        <mesh
          name="GlassUpper2"
          geometry={nodes.GlassUpper2.geometry}
          material={materials.Glass}
          position={[29.071, 28.449, 33.538]}
          scale={[0.2, 5.375, 12.093]}
        >
          <mesh
            name="GlassSupUpper1001"
            geometry={nodes.GlassSupUpper1001.geometry}
            material={materials.glasswindowsSupport}
            position={[-1.785, -0.034, 0.019]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[1.028, 5, 1.664]}
          />
        </mesh>
        <mesh
          name="GlassUpperM"
          geometry={nodes.GlassUpperM.geometry}
          material={materials.Glass}
          position={[37.077, 27.001, 0.255]}
          scale={[0.2, 3.777, 14.626]}
        />
        <mesh
          name="GlassLowerM"
          geometry={nodes.GlassLowerM.geometry}
          material={materials.Glass}
          position={[32.217, 11.157, -0.203]}
          scale={[0.2, 6.268, 14.38]}
        />
        <mesh
          name="EntranceDoorChoukat"
          geometry={nodes.EntranceDoorChoukat.geometry}
          material={nodes.EntranceDoorChoukat.material}
          position={[31.621, 10.895, 0.346]}
          scale={[0.575, 1, 0.379]}
        />
        <mesh
          name="UpperFrontGrill"
          geometry={nodes.UpperFrontGrill.geometry}
          material={materials.glasswindowsSupport}
          position={[29.733, 25.792, 0.143]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[14.099, 2.419, 2.419]}
        />
        <mesh
          name="Floor2SajjaBlue"
          geometry={nodes.Floor2SajjaBlue.geometry}
          material={
            materials[
              "asset_base_id:3e8f92f3-2840-47af-afaa-8cd11f9bc641 asset_type:m"
            ]
          }
          position={[29.433, 34.866, -33.163]}
          scale={[1, 1, 21.272]}
        />
        <mesh
          name="Cube009"
          geometry={nodes.Cube009.geometry}
          material={materials.Plaster}
          position={[59.819, 18.349, 0]}
          scale={[30.325, 21.308, 53.31]}
        />
        <mesh
          name="TerraceDecor1"
          geometry={nodes.TerraceDecor1.geometry}
          material={materials.redRod}
          position={[39.515, 43.545, -6.5]}
          scale={[1, 7.503, 5.689]}
        />
        <mesh
          name="TerraceDecor2"
          geometry={nodes.TerraceDecor2.geometry}
          material={materials.redRod}
          position={[39.515, 43.545, 6.5]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 7.503, 5.689]}
        />
        <mesh
          name="GlassLower1"
          geometry={nodes.GlassLower1.geometry}
          material={materials.Glass}
          position={[29.581, 11.416, -33.655]}
          scale={[0.2, 5.985, 20.117]}
        >
          <mesh
            name="GlassSupLower1"
            geometry={nodes.GlassSupLower1.geometry}
            material={materials.glasswindowsSupport}
            position={[-1.785, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.923, 5, 1.001]}
          />
        </mesh>
        <mesh
          name="DEPARTMENT_OF"
          geometry={nodes.DEPARTMENT_OF.geometry}
          material={materials.redRod}
          position={[28.088, 20.94, -10.034]}
          rotation={[1.571, -0.018, 1.571]}
          scale={0.136}
        />
        <mesh
          name="DEPARTMENT_OF001"
          geometry={nodes.DEPARTMENT_OF001.geometry}
          material={materials["redRod.001"]}
          position={[27.832, 22.364, -4.847]}
          rotation={[1.571, -0.018, 1.571]}
          scale={0.109}
        />
        <mesh
          name="GlassLower1001"
          geometry={nodes.GlassLower1001.geometry}
          material={materials.Glass}
          position={[59.872, 11.416, -54.098]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.2, 5.985, 30.51]}
        >
          <mesh
            name="GlassSupLower1001"
            geometry={nodes.GlassSupLower1001.geometry}
            material={materials.glasswindowsSupport}
            position={[-1.785, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.923, 5, 1.001]}
          />
        </mesh>
        <mesh
          name="GlassLower1002"
          geometry={nodes.GlassLower1002.geometry}
          material={materials.Glass}
          position={[59.872, 11.416, 54.065]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.2, 5.985, 30.51]}
        >
          <mesh
            name="GlassSupLower1002"
            geometry={nodes.GlassSupLower1002.geometry}
            material={materials.glasswindowsSupport}
            position={[-1.785, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.923, 5, 1.001]}
          />
        </mesh>
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          position={[59.372, 20.338, -53.654]}
          scale={[30.731, 3.412, 0.451]}
        />
        <mesh
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={nodes.Cube001.material}
          position={[59.372, 20.338, 53.871]}
          scale={[30.731, 3.412, 0.451]}
        />
        <mesh
          name="Cube002"
          geometry={nodes.Cube002.geometry}
          material={nodes.Cube002.material}
          position={[59.372, 32.544, 54.724]}
          scale={[30.731, 0.427, 1.404]}
        />
        <mesh
          name="Cube003"
          geometry={nodes.Cube003.geometry}
          material={nodes.Cube003.material}
          position={[59.372, 32.544, -54.799]}
          scale={[30.731, 0.427, 1.404]}
        />
        <mesh
          name="Cube004"
          geometry={nodes.Cube004.geometry}
          material={materials.Plaster}
          position={[59.819, 18.349, 0]}
          scale={[30.325, 21.308, 53.31]}
        />
        <mesh
          name="Cube005"
          geometry={nodes.Cube005.geometry}
          material={materials.Plaster}
          position={[59.819, 18.349, 0]}
          scale={[30.325, 21.308, 53.31]}
        />
        <mesh
          name="Cube006"
          geometry={nodes.Cube006.geometry}
          material={materials.Plaster}
          position={[59.819, 18.349, 0]}
          scale={[30.325, 21.308, 53.31]}
        />
        <mesh
          name="Cube007"
          geometry={nodes.Cube007.geometry}
          material={nodes.Cube007.material}
          position={[111.266, 18.078, -0.021]}
          scale={[21.218, 21.456, 68.586]}
        />
        <mesh
          name="Cube008"
          geometry={nodes.Cube008.geometry}
          material={nodes.Cube008.material}
          position={[113.367, 32.544, 72.528]}
          scale={[22.399, 0.427, 4.578]}
        />
        <mesh
          name="Cube010"
          geometry={nodes.Cube010.geometry}
          material={nodes.Cube010.material}
          position={[113.367, 32.544, -72.534]}
          scale={[22.399, 0.427, 4.578]}
        />
        <mesh
          name="Cube011"
          geometry={nodes.Cube011.geometry}
          material={nodes.Cube011.material}
          position={[129.903, 44.161, 0.109]}
          scale={[1, 5.115, 6.448]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/entranceBioTech.glb");
